eureka:
  instance:
    metadata-map:
      type: data
      label: Superset Proxy
      superset: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
spring:
  main:
    lazy-initialization: true
  application:
    name: superset-proxy
  datasource:
    url: jdbc:postgresql://postgres:5432/amp
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      host: cache
      port: 6379
      password: admin

viz:
  superset:
    url: http://superset:8088
    database: amp
    schema: public
server:
  port: 8090
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
    enabled-methods: GET,POST

management:
  endpoints:
    web:
      exposure:
        include: health
