eureka:
  instance:
    metadata-map:
      type: data
      label: Superset Proxy
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka

spring:
  application:
    name: superset-proxy

superset:
  url: https://superset.alive.dgstg.org/

server:
  port: 8080



management:
  endpoints:
    web:
      exposure:
        include: health
