services:
  postgres:
    image: postgres:16.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: viz
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend-api:


  eureka:
    build:
      context: ./registry
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms1024m -XX:+UseG1GC -XX:InitialHeapSize=1024m -XX:MaxHeapSize=1024m -XX:+ParallelRefProcEnabled "
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 50s
    ports:
      - "8761:8761"
    depends_on:
      - postgres
    networks:
      backend-api:


  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/viz"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "admin"
      JAVA_OPTS: "-Xmx512m -Xms512m -XX:+UseG1GC -XX:InitialHeapSize=512m -XX:MaxHeapSize=512m -XX:+ParallelRefProcEnabled"
    ports:
      - "8762:8762"
    depends_on:
      - postgres
      - eureka
    networks:
      backend-api:


  api-security:
    build:
      context: ./api-security
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/viz"
      JAVA_OPTS: "-Xmx512m -Xms512m -XX:+UseG1GC -XX:InitialHeapSize=512m -XX:MaxHeapSize=512m -XX:+ParallelRefProcEnabled "
    ports:
      - "8763:8763"
    depends_on:
      - postgres
      - eureka
    networks:
      backend-api:


  superset-proxy:
    build:
      context: ./superset-proxy
      dockerfile: Dockerfile
    environment:
      VIZ_SUPERSET_URL: "https://your-superset-instance.example.com/"
      VIZ_SUPERSET_WARMUP_TOP: "100"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/viz"
      JAVA_OPTS: "-Xmx512m -Xms512m -XX:+UseG1GC -XX:InitialHeapSize=512m -XX:MaxHeapSize=512m -XX:+ParallelRefProcEnabled "
      SPRING_PROFILES_ACTIVE: "dev"
      EUREKA_INSTANCE_METADATA-MAP_SUPERSET: "true"
      EUREKA_INSTANCE_METADATA-MAP_TYPE: "data"
      EUREKA_INSTANCE_METADATA-MAP_LABEL: "Superset Data"
      SPRING_APPLICATION_NAME: "superset-proxy"
      SPRING_DATA_REDIS_HOST: "cache"
      SPRING_DATA_REDIS_PORT: "6379"
      SPRING_DATA_REDIS_PASSWORD: "admin"
      SPRING_DATA_CACHE_TYPE: "redis"
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - cache
      - eureka
    networks:
      backend-api:


  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    ports:
      - "6379:6379"
    networks:
      - backend-api

volumes:
  cache:


networks:
  backend-api:
