package org.devgateway.viz.commons.services;

import com.google.common.collect.ImmutableList;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import org.apache.commons.lang3.StringUtils;
import org.devgateway.viz.commons.domain.Category;
import org.devgateway.viz.commons.domain.DatasetRecord;
import org.devgateway.viz.commons.domain.Language;
import org.devgateway.viz.commons.domain.LocaleText;
import org.devgateway.viz.commons.domain.QCategory;
import org.devgateway.viz.commons.domain.Styles;
import org.devgateway.viz.commons.domain.metadata.DimensionDefinition;
import org.devgateway.viz.commons.pojo.Dimension;
import org.devgateway.viz.commons.pojo.request.CategoryRequest;
import org.devgateway.viz.commons.repositories.CategoryRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Generated by Spring Data Generator on 23/04/2020
 */
@Service
public class CategoryService {
    private final Logger logger = LoggerFactory.getLogger(this.getClass());

    @PersistenceContext
    private EntityManager em;

    @Autowired
    private DimensionDefinitionService dimensionDefinitionService;

    private final static List<String> NOT_ALLOWED_CATEGORIES_TYPES_FOR_EDITING =
            ImmutableList.of("MeasureDefinition", "DimensionDefinition", "FilterDefinition", "MeasureGroup", "Dataset");


    public String codify(String label) {
        return Utils.codify(label);
    }

    private CategoryRepository categoryRepository;


    @Autowired
    public CategoryService(final CategoryRepository categoryRepository, final GoogleTranslationService googleTranslationService) {
        this.categoryRepository = categoryRepository;
    }


    private Category createNewCategory(final Class<Category> tClass) {
        try {
            Category t = tClass.getConstructor(null).newInstance();

            return t;
        } catch (InstantiationException e) {
            logger.error(e.getMessage(), e);
        } catch (IllegalAccessException | NoSuchMethodException e) {
            logger.error(e.getMessage(), e);
        } catch (InvocationTargetException e) {
            logger.error(e.getMessage(), e);
        }
        return null;
    }


    public List<Category> getAllCategories() {
        return this.categoryRepository.findAll();
    }

    public List<Category> getCategoriesForAdmin() {
        return this.categoryRepository.findAll().stream()
                .filter(c -> !NOT_ALLOWED_CATEGORIES_TYPES_FOR_EDITING.contains(c.getType()))
                .collect(Collectors.toList());
    }


    public Category createIfNotExist(String value, String code, final Class type) {

        return createIfNotExist(value, code, null, type, null, null, true, null, Optional.empty(), Optional.empty());

    }

    public Category createIfNotExist(String value, String code, final Class type, Integer position) {

        return createIfNotExist(value, code, null, type, position, null, true, null, Optional.empty(), Optional.empty());

    }


    public Category createIfNotExist(String value, final Class type) {
        return createIfNotExist(value, codify(value), null, type, null, null, true, null, Optional.empty(), Optional.empty());

    }

    public Category createIfNotExist(String value, final Class type, Styles styles) {
        return createIfNotExist(value, codify(value), null, type, null, null, true, null, Optional.of(styles), Optional.empty());
    }

    public Category createIfNotExist(final String value, final Class type, Integer position) {
        return createIfNotExist(value, codify(value), null, type, position, null, true, null, Optional.empty(), Optional.empty());
    }


    public Category createIfNotExist(String value, String code, final Class type, Integer position, Styles styles) {
        return createIfNotExist(value, code, null, type, position, null, true, null, Optional.of(styles), Optional.empty());
    }

    public Category createIfNotExist(final String value, final Class type, Integer position, Styles styles, List<LocaleText> translations) {
        return createIfNotExist(value, codify(value), null, type, position, null, true, null, Optional.of(styles), Optional.of(translations));
    }

    public Category createIfNotExist(final String value, final Class type, Integer position, Styles styles) {
        return createIfNotExist(value, codify(value), null, type, position, null, true, null, Optional.of(styles), Optional.empty());
    }

    public Category createIfNotExist(final String value, final Class type, List<LocaleText> translations) {
        return createIfNotExist(value, codify(value), null, type, null, null, true, null, Optional.empty(), Optional.of(translations));
    }

    public Category get(String value, final Class type) {
        return createIfNotExist(value, codify(value), null, type, null, null, false, null, Optional.empty(), Optional.empty());
    }

    public Category getByCode(String code, final Class type) {
        QCategory cat = QCategory.category;
        String typeName = type.getName().substring(type.getName().lastIndexOf(".") + 1);
        Iterable<Category> items = categoryRepository
                .findAll(cat.code.equalsIgnoreCase(code)
                        .and(cat.type.equalsIgnoreCase(typeName)));
        if (items.iterator().hasNext()) {
            return items.iterator().next();
        } else {
            return null;
        }

    }

    public Category save(Category category) {
        return categoryRepository.save(category);
    }

    public Category getByValue(String value, final Class type) {
        return createIfNotExist(value, codify(value), null, type, null, null, false, null, Optional.empty(), Optional.empty());
    }


    private Category createIfNotExist(final String value, String code, List<LocaleText> labels, final Class type, final Integer position, List<LocaleText> descriptions, final Boolean create, Category parent, Optional<Styles> styles, Optional<List<LocaleText>> translations) {
        try {

            if (value != null && value.isEmpty() && create) {
                return null; //null value will never create a new category
            }

            if ((value == null || value.trim().isEmpty()) && create) {
                throw new Exception("Value can't be null if create is true");
            }

            String typeName = type.getName().substring(type.getName().lastIndexOf(".") + 1);
            QCategory cat = QCategory.category;
            Iterable<Category> items = (code != null) ? categoryRepository.findAll(cat.code.equalsIgnoreCase(code).and(cat.type.equalsIgnoreCase(typeName))) : categoryRepository.findAll(cat.value.equalsIgnoreCase(value).and(cat.type.equalsIgnoreCase(typeName)));

            if (items.iterator().hasNext()) {
                // Always update translations if the current are empty and we have new ones.
                Category category = items.iterator().next();
                if (translations != null && translations.isPresent() && !translations.get().isEmpty() && category.getLabels().isEmpty()) {
                    category.setLabels(translations.get());
                }
                return items.iterator().next();
            } else if (create) {
                final Category retValue = createNewCategory(type);
                retValue.setValue(value);
                retValue.setCode(code.toUpperCase());
                retValue.setPosition(position);
                retValue.setDescriptions(descriptions);
                retValue.setLabels(labels);
                retValue.setParent(parent);
                retValue.setCategoryStyle(styles.orElse(null));
                retValue.setLabels(translations.orElse(null));
                categoryRepository.saveAndFlush(retValue);
                return retValue;
            } else {
                return null;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public Category getCategoryById(final Long id) {
        return categoryRepository.findById(id).get();
    }

    public void deleteCategory(final Long id) {
        categoryRepository.delete(getCategoryById(id));
    }

    public Category updateCategory(final Long id, final CategoryRequest categoryRequest) {
        final Category category = getCategoryById(id);
        if (StringUtils.isNotBlank(categoryRequest.getValue())) {
            category.setValue(categoryRequest.getValue());
        }

        if (categoryRequest.getPosition() != null) {
            category.setPosition(categoryRequest.getPosition());
        }

        if (categoryRequest.getCategoryStyle() != null) {
            category.setCategoryStyle(categoryRequest.getCategoryStyle());
        }

        if (categoryRequest.getLabels() != null) {
            List<LocaleText> labels = new ArrayList<>();
            categoryRequest.getLabels().forEach((language, text) -> {
                LocaleText localeText = new LocaleText();
                localeText.setLanguage(getLanguage(language));
                localeText.setText(text);
                labels.add(localeText);
            });

            category.setLabels(labels);
        }

        return categoryRepository.saveAndFlush(category);
    }

    public Language getLanguage(String language) {
        if (language != null && !language.trim().isEmpty()) {
            Language l = (Language) get(codify(language), Language.class);
            if (l == null) {
                l = (Language) createIfNotExist(language, codify(language), Language.class);
            }

            return l;
        }

        return null;
    }

    /**
     * Look for categories that are not in use in any DatasetRecord (the main entity in the API) and delete them.
     */
    public void clearCategories() {
        List<Dimension> dimensions = dimensionDefinitionService.getDimensions();
        List<String> dimensionTypes = dimensions.stream().map(m -> m.getType()).collect(Collectors.toList());
        Query query = em.createQuery("select c from Category c where c.type in :types")
                .setParameter("types", dimensionTypes);
        List<Category> categories = query.getResultList();
        categories.forEach(c -> {
            DimensionDefinition dimensionDefinition = dimensionDefinitionService.getDimensionDefinitionByFieldType(c.getType());
            String fieldName = dimensionDefinition.getField();
            DatasetRecord item = (DatasetRecord) em.createQuery("select d from DatasetRecord d where d." + fieldName + ".id = :id")
                    .setParameter("id", c.getId()).getResultList().stream().findFirst().orElse(null);
            if (item == null) {
                logger.info("Category " + c.getValue() + " is NOT used in any item. Deleting...");
                categoryRepository.delete(c);
            }
        });
    }
}
