# The SQL dialect makes Hibernate generate better SQL for the chosen database

spring.datasource.hikari.connection-timeout=50000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=900000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.pool-name=ConnPool

spring.jpa.properties.hibernate.dialect=org.devgateway.viz.commons.dialect.PostgreSQL10SchemaDialect
# Hibernate ddl auto (create, create-drop, validate, update)
liquibase.change-log=classpath:liquibase-changeLog.xml
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:liquibase-changeLog.xml
#spring.datasource.url=jdbc:postgresql://postgres:5432/viz
spring.datasource.url=jdbc:postgresql://localhost:5432/viz
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


viz.startup.import=false
viz.initial.config=true

viz.date.format='DD/MM/YYYY'

management.port=8080
management.ssl.enable=true
management.ssl.key-store=classpath:management.jks
management.ssl.key-password=secret
spring.security.user.name=admin
spring.security.user.password=admin
eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
viz.translations.enabled=false
viz.ai.translation.key=none
google.cloud.key=NONE
google.translation.enable=false
google.translation.app=NONE

