server.port=8763
spring.application.name=api-security
***REMOVED***eureka.instance.preferIpAddress=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
management.endpoints.web.exposure.include=*
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.datasource.username=postgres
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.url=jdbc:postgresql://localhost:5432/viz

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packagesToScan=org.devgateway.viz.zuul
springdoc.swagger-ui.enabled=true
