server.port=8763
spring.application.name=api-security
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:postgresql://postgres:5432/viz
spring.datasource.username=postgres
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
eureka.instance.preferIpAddress=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://eureka:8761/eureka}
management.endpoints.web.exposure.include=*
ribbon.ReadTimeout=45000
ribbon.ConnectTimeout=45000
zuul.host.connect-timeout-millis=45000
zuul.host.socket-timeout-millis=45000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=45000
hystrix.command.default.execution.timeout.enabled=false
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.error.include-message=always
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
