name: Build And Release API Security

on:
  workflow_dispatch:
  push:
    paths:
      - ./api-security/**
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build_and_release_api_security:
    uses: ./.github/workflows/release-template.yml
    with:
      project_name: 'api-security'
      docker_buildx_cache_to: 'api-security'
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      dockerfile: 'Dockerfile'
      docker_build_context: './api-security'
      docker_buildx_cache_from: 'api-security'
      pre_release: 'true'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}




