name: Build And Release Superset Proxy

on:
  workflow_dispatch:
  push:
    paths:
      - ./superset-proxy/**
    branches:
      - production
      - release/*

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build_and_release_superset_proxy:
    uses: ./.github/workflows/release-template.yml
    with:
      project_name: 'superset-proxy'
      docker_buildx_cache_to: 'superset-proxy'
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      dockerfile: 'Dockerfile'
      docker_build_context: './superset-proxy'
      docker_buildx_cache_from: 'superset-proxy'
      pre_release: 'false'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}




