name: Build And Pre Release API Gateway

on:
  workflow_dispatch:
  push:
    paths:
      - api-gateway/**
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build_and_release_api_gateway:
    uses: ./.github/workflows/release-template.yml
    with:
      project_name: 'api-gateway'
      docker_buildx_cache_to: 'api-gateway'
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      dockerfile: 'Dockerfile'
      docker_build_context: './api-gateway'
      docker_buildx_cache_from: 'api-gateway'
      pre_release: 'true'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}




